### ISSUE TITLE
cozytouch not recognized on windows 10

### ISSUE THREAD

**Issue by jugla** [biker91620/ha-cozytouch#15]
I've installed all package on **windows 10**.

I have use configuration.yaml

```
#cozytouch
switch:
  - platform: cozytouch
    username: xxxx@yyy.zz
    password: mypassword
    
 #end cozytouch
```

I fall on this error:
```
2020-01-04 03:33:10 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=12 from 2020-01-04 02:25:31.773354)

2020-01-04 03:33:12 ERROR (MainThread) [homeassistant.config] Platform error: switch - Integration 'cozytouch' not found.
```

Thanks in advance
Philippe

**Comment by jugla** [comment]
I've installed the cozytouch on Fedora Core 31 (on virtual box). Exactly the same error.

**Comment by jugla** [comment]
Installation process
```
[homeassistant@localhost famille]$ cd /opt/homeassistant
[homeassistant@localhost homeassistant]$ python3.8 -m venv .
[homeassistant@localhost homeassistant]$ source bin/activate
(homeassistant) [homeassistant@localhost homeassistant]$ pip3 install git+https://github.com/biker91620/cozypy.git
Collecting git+https://github.com/biker91620/cozypy.git
  Cloning https://github.com/biker91620/cozypy.git to /tmp/pip-req-build-1wr4t24a
  Running command git clone -q https://github.com/biker91620/cozypy.git /tmp/pip-req-build-1wr4t24a
Requirement already satisfied: requests in ./lib/python3.8/site-packages (from cozypy==1.1.1) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python3.8/site-packages (from requests->cozypy==1.1.1) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.8/site-packages (from requests->cozypy==1.1.1) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.8/site-packages (from requests->cozypy==1.1.1) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in ./lib/python3.8/site-packages (from requests->cozypy==1.1.1) (2.8)
Installing collected packages: cozypy
  Running setup.py install for cozypy ... done
Successfully installed cozypy-1.1.1
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
The configuration.yaml file 
```
#cozytouch
switch:
  - platform: cozytouch
    username: xxxx@xxxx
    password: yyyyy
#end cozytouch
```

**Comment by jugla** [comment]
Here a solution : let's say a workaround .
Download the zip file from git `ha-cozytouch-master.zip`
Unzip
(Hereafter directory path are under ferdoracore 31 with python 3.8)
Copy directory `ha-cozytouch-master/custom_components/cozytouch` in homeassistant directory `/opt/homeassistant/lib64/python3.8/site-packages/homeassistant/components/`
**All python files inside cozytouch directory** have to be updated such as  the string `from custom_components.cozytouch` is replaced  by `from homeassistant.components.cozytouch`
Restart Home assistant.

Here a sample of configuration.yaml file where the username/password are those from the cozytouch application
```
#cozytouch
sensor:
  - platform: cozytouch
    username: xxxx@xxxx
    password: yyyyy
climate:
  - platform: cozytouch
    username: xxxx@xxxx
    password: yyyyy
#end cozytouch
```

**The results is fantastic : great job biker61920 !**
